name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-darwin:
        runs-on: macOS-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    sudo xcode-select -s /Library/Developer/CommandLineTools
                    mkdir build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    make -j8
                    make create_zip
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    path: build/Climber_*.zip

    build-windows-x86:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
                run: |
                    md build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
                    nmake create_zip
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    path: build/Climber_*.zip

    build-windows-x64:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
                run: |
                    md build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
                    nmake create_zip
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    path: build/Climber_*.zip
