name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-darwin:

    runs-on: macOS-10.14

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j8
        make create_zip
      

      
#   build-windows:
#     runs-on: windows-2019

#     steps:
#       - uses: actions/checkout@v2
      
