name: Build Release MacOS

on:
    release:
        types: [released]

jobs:
    build:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
                    md build
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
                    nmake create_zip
            -   name: Upload Release Binary
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: build/Climber_*.zip
                    tag: ${{ github.ref }}
                    file_glob: true
                    overwrite: true
